ex1:
	gcc ex1.c -o ex1.out -lpthread
	
ex2:
	gcc ex2.c matriz.c -o ex2.out -lpthread -lm

ex2_bm:
	gcc ex2_benchmark.c matriz.c -o ex2_bm.out -lpthread -lm
	
clean:
	rm *.out

clean_output:
	rm *.txt

clean_matrix:
	rm *.in